HelpInfo,C:\Microsemi\Libero_v11.6\Synopsys\fpga_J-2015.03M-3\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_v11.6\Synopsys\fpga_J-2015.03M-3\bin\mbin\assistant
Implementation;Synthesis;RootName:build
Implementation;Synthesis||(null)||Info: Interrupted by user!||(null);(null)||(null);(null)
Implementation;Compile;RootName:build
Implementation;Compile||(null)||Please refer to the log file for details about 3 Warning(s) , 8 Info(s)||build_compile_log.log;liberoaction://open_report/file/build_compile_log.log||(null);(null)
Implementation;Place and Route;RootName:build
Implementation;Place and Route||(null)||Please refer to the log file for details about 2 Info(s)||build_layout_log.log;liberoaction://open_report/file/build_layout_log.log||(null);(null)
Implementation;Generate Bitstream;RootName:build
Implementation;Generate Bitstream||(null)||Please refer to the log file for details||build_generateBitstream.log;liberoaction://open_report/file/build_generateBitstream.log||(null);(null)
